name: VirtualDeck
options:
  bundleIdPrefix: com.virtualdeck
  deploymentTarget:
    iOS: "17.0"

targets:
  VirtualDeck:
    type: application
    platform: iOS
    sources:
      - VirtualDeckApp.swift
      - Models
      - Views
      - ViewModels
      - Services
    settings:
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      CODE_SIGN_STYLE: Manual
      CODE_SIGNING_ALLOWED: NO
      SWIFT_VERSION: "5.0"
