name: VirtualDeck
options:
  bundleIdPrefix: com.virtualdeck
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.4"

settings:
  SWIFT_VERSION: "5.0"

targets:
  VirtualDeck:
    type: application
    platform: iOS
    sources:
      - path: VirtualDeckApp.swift
      - path: Models
      - path: Views
      - path: ViewModels
      - path: Services
    resources:
      - path: Resources
        buildPhase: resources
    settings:
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      CODE_SIGN_STYLE: Manual
      CODE_SIGNING_ALLOWED: NO
